version: "3.9"

services:
  jellyfin-bot:
    build: .
    container_name: jellyfin-telegram-bot
    restart: unless-stopped
    volumes:
      - ./config:/app/config
      - ./data:/app/data
      - ./logs:/app/logs
